### ISSUE TITLE
Debian install: package not found?

### ISSUE THREAD

**Issue by p2635** [leapcode/bitmask-dev#11] opened 2017-10-11 14:39 UTC
Hi all, I'm trying to install bitmask usinig the instructions as listed on here:
https://dl.bitmask.net/linux/

It does successfully do apt update but then when it tries to install bitmask, the package is not found.

Am I doing something wrong?

**Comment by micah** [comment] 2017-10-17 17:33
Hello,

Can you tell us what operating system and version you are running? It may be that you are running an unsupported version. You can always install the bundle, instead of the package, if you would like.

**Comment by AreYouLoco** [comment] 2017-10-24 16:54
Hi I can confirm that installing from repo doesnt work I checked release, staging and master for stretch. Going manually to the https://deb.leap.se/client gives me error 403. That might be the reason.

Using Debian stretch. I used to have bitmask installed but accidentally I removed it and now I can only use the standalone version. And I liked the one packed for debian much more. Because of the tray icon mostly :D

**Comment by meskio** [comment] 2017-10-26 07:52
Yes, it gives a 403. But adding it to the sources list as described in https://dl.bitmask.net/linux/ works fine.

@p2635 and @AreYouLoco if you want to pass by our irc channel (#leap @ irc.freenode.net) we can look into your problems more directly.

I'm closing the issue, as I tested the repo for stretch and works fine for me. Feel free to reopen it if you still have issues, or to create an issue in our bug tracker: https://0xacab.org/leap/bitmask-dev/issues/

**Closed by meskio** 2017-10-26 07:52 UTC
